# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: yandex/cloud/ai/stt/v2/stt_service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.api.annotations_pb2
import google.protobuf.duration_pb2
import yandex.cloud.api.operation_pb2
import yandex.cloud.operation.operation_pb2
import yandex.cloud.ai.stt.v2.stt_service_pb2


class SttServiceBase(abc.ABC):

    @abc.abstractmethod
    async def LongRunningRecognize(self, stream: 'grpclib.server.Stream[yandex.cloud.ai.stt.v2.stt_service_pb2.LongRunningRecognitionRequest, yandex.cloud.operation.operation_pb2.Operation]') -> None:
        pass

    @abc.abstractmethod
    async def StreamingRecognize(self, stream: 'grpclib.server.Stream[yandex.cloud.ai.stt.v2.stt_service_pb2.StreamingRecognitionRequest, yandex.cloud.ai.stt.v2.stt_service_pb2.StreamingRecognitionResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/yandex.cloud.ai.stt.v2.SttService/LongRunningRecognize': grpclib.const.Handler(
                self.LongRunningRecognize,
                grpclib.const.Cardinality.UNARY_UNARY,
                yandex.cloud.ai.stt.v2.stt_service_pb2.LongRunningRecognitionRequest,
                yandex.cloud.operation.operation_pb2.Operation,
            ),
            '/yandex.cloud.ai.stt.v2.SttService/StreamingRecognize': grpclib.const.Handler(
                self.StreamingRecognize,
                grpclib.const.Cardinality.STREAM_STREAM,
                yandex.cloud.ai.stt.v2.stt_service_pb2.StreamingRecognitionRequest,
                yandex.cloud.ai.stt.v2.stt_service_pb2.StreamingRecognitionResponse,
            ),
        }


class SttServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.LongRunningRecognize = grpclib.client.UnaryUnaryMethod(
            channel,
            '/yandex.cloud.ai.stt.v2.SttService/LongRunningRecognize',
            yandex.cloud.ai.stt.v2.stt_service_pb2.LongRunningRecognitionRequest,
            yandex.cloud.operation.operation_pb2.Operation,
        )
        self.StreamingRecognize = grpclib.client.StreamStreamMethod(
            channel,
            '/yandex.cloud.ai.stt.v2.SttService/StreamingRecognize',
            yandex.cloud.ai.stt.v2.stt_service_pb2.StreamingRecognitionRequest,
            yandex.cloud.ai.stt.v2.stt_service_pb2.StreamingRecognitionResponse,
        )
